export const ERROR_CODES = {
  // Auth-related
  AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_NOT_CONFIRMED: "AUTH_NOT_CONFIRMED",
  AUTH_FAILED: "AUTH_FAILED",
  AUTH_UNSUPPORTED_METHOD: "AUTH_UNSUPPORTED_METHOD",
  AUTH_PASSWORD_RESET_REQUIRED: "AUTH_PASSWORD_RESET_REQUIRED",
  AUTH_USER_EXISTS: "AUTH_USER_EXISTS",
  AUTH_NOT_LOGGED_IN: "AUTH_NOT_LOGGED_IN",
  AUTH_CONFIRMATION_FAILED: "AUTH_CONFIRMATION_FAILED",
  AUTH_RESEND_FAILED: "AUTH_RESEND_FAILED",
  AUTH_PASSWORD_RESET_FAILED: "AUTH_PASSWORD_RESET_FAILED",
  AUTH_PASSWORD_RESET_SUBMIT_FAILED: "AUTH_PASSWORD_RESET_SUBMIT_FAILED",

  // Realtime/WebSocket
  WS_UNAUTHORIZED: "WS_UNAUTHORIZED",
  WS_CONNECTION_FAILED: "WS_CONNECTION_FAILED",
  WS_SUBSCRIPTION_FAILED: "WS_SUBSCRIPTION_FAILED",
  REALTIME_NOT_CONNECTED: "REALTIME_NOT_CONNECTED",
  REALTIME_CONNECTION_FAILED: "REALTIME_CONNECTION_FAILED",
  REALTIME_FATAL: "REALTIME_FATAL",
  REALTIME_TIMEOUT: "REALTIME_TIMEOUT",

  // API errors
  API_BAD_REQUEST: "API_BAD_REQUEST", // 400
  API_UNAUTHORIZED: "API_UNAUTHORIZED", // 401
  API_FORBIDDEN: "API_FORBIDDEN", // 403
  API_NOT_FOUND: "API_NOT_FOUND", // 404
  API_CONFLICT: "API_CONFLICT", // 409
  API_UNPROCESSABLE_ENTITY: "API_UNPROCESSABLE_ENTITY", // 422
  API_SERVER_ERROR: "API_SERVER_ERROR", // 5xx
  API_FATAL: "API_FATAL", // fallback
};
